services:
  - type: web
    name: ojo-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://ojo-backend.onrender.com/api