services:
  # Backend Service
  - type: web
    name: ojo-backend
    env: node
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        value: 4000
      - key: TIDB_USERNAME
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: TIDB_DATABASE
        value: people_insights
      - key: GEMINI_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: ojo-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://ojo-backend.onrender.com/api